CREATE DATABASE DE3THI
go
USE DE3THI
-- TAO BANG
CREATE TABLE DOCGIA
(
    MADG CHAR(5) PRIMARY KEY,
    HOTEN VARCHAR(30),
    NGAYSINH SMALLDATETIME,
    DIACHI VARCHAR(30),
    SODT VARCHAR(15),
)
CREATE TABLE SACH
(
    MASACH CHAR(5) PRIMARY KEY,
    TENSACH VARCHAR(25),
    THELOAI VARCHAR(25),
    NHAXUATBAN VARCHAR(30)
)
CREATE TABLE PHIEUTHUE
(
    MAPT CHAR(5) PRIMARY KEY,
    MADG CHAR(5),
    NGAYTHUE SMALLDATETIME,
    NGAYTRA SMALLDATETIME,
    SOSACHTHUE INT,
    CONSTRAINT FK_MADG FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)
)

CREATE TABLE CHITIET_PT
(
    MAPT CHAR(5),
    MASACH CHAR(5),
    CONSTRAINT PK_MAPT_MASACH PRIMARY KEY (MAPT,MASACH),
    CONSTRAINT FK_MAPT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT),
    CONSTRAINT FK_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH),
)
SET DATEFORMAT DMY
--TRIGGER
--2.1 
GO
CREATE TRIGGER DE3_PHIEUTHUE ON PHIEUTHUE
FOR INSERT, UPDATE 
AS 
BEGIN
    DECLARE @NGAYTHUE SMALLDATETIME, @NGAYTRA SMALLDATETIME
    SELECT @NGAYTHUE = NGAYTHUE, @NGAYTRA = NGAYTRA
    FROM INSERTED
    IF(DATEDIFF(NGAYTHUE, NGAYTRA) > 10)
    BEGIN
        print 'Ngay thue khong duoc qua 10 ngay'
        rollback TRANSACTION
    END
    else
    BEGIN
        print 'THUE THANH CONG'
    END
END
--DATA TEST
INSERT INTO DOCGIA
    (MADG,HOTEN,NGAYSINH,DIACHI,SODT)
VALUES
    ('DG01', 'NGUYEN VAN A', '01/01/2001', '123 PHI', '0902123456')
INSERT INTO PHIEUTHUE
    (MAPT,MADG,NGAYTHUE,NGAYTRA,SOSACHTHUE)
VALUES
    ('PT01', 'DG01', '1/1/2020', '10/1/2020', 10)
UPDATE PHIEUTHUE
SET SOSACHTHUE=0
WHERE MAPT='PT01'
--2.2
GO
CREATE TRIGGER TRGDE22_PHIEUTHUE ON PHIEUTHUE
FOR UPDATE, INSERT
AS 
BEGIN
    DECLARE @SOSACHTHUE int, @MaPT char(5), @SOLUONGSACHCT INT
    SELECT @SOSACHTHUE = SOSACHTHUE, @MaPT = MAPT
    FROM INSERTED
    SELECT @SOLUONGSACHCT = COUNT(CT.MaSach)
    FROM CHITIET_PT CT
    WHERE CT.MASACH = @MaPT
    IF(@SOLUONGSACHCT <> @SOSACHTHUE)
    BEGIN
        UPDATE PHIEUTHUE
        Set SOSACHTHUE = @SOLUONGSACHCT
        WHERE MAPT = @MaPT
    END
END

GO
CREATE TRIGGER TRGDE22_CTPHIEUTHUE ON CHITIET_PT
AFTER INSERT, UPDATE
AS 
BEGIN
    DECLARE @MaSach char(5), @MaPT char(5), @SOLUONGSACHCT INT, @SOSACHTHUE INT
    SELECT @MaSach = MASACH, @MaPT = MAPT
    FROM INSERTED
    -- lấy field số sách thuê của Phiếu thuê đó
    SELECT @SOSACHTHUE = SOSACHTHUE
    FROM PHIEUTHUE PT
    WHERE PT.MAPT = @MaPT
    -- đếm số lượng sách của phiếu thuê đó AFTER insert, update
    SELECT @SOLUONGSACHCT = COUNT(CT.MaSach)
    FROM CHITIET_PT CT
    WHERE CT.MAPT = @MaPT
    -- set lại
    IF(@SOLUONGSACHCT <> @SOSACHTHUE)
    BEGIN
        UPDATE PHIEUTHUE
        Set SOSACHTHUE = @SOLUONGSACHCT
        WHERE MAPT = @MaPT
    END
END

--DATA TEST....
INSERT INTO SACH
    (MASACH,TENSACH,THELOAI,NHAXUATBAN)
VALUES
    ('S01', 'TIN HOC', 'TIN HOC', 'VN')
INSERT INTO CHITIET_PT
    (MAPT,MASACH)
VALUES
    ('PT01', 'S01')
--SQL
--CAU1
SELECT DG.MADG, HOTEN
FROM DOCGIA DG, PHIEUTHUE PT, CHITIET_PT CT1, SACH
WHERE DG.MADG=PT.MADG AND PT.MAPT=CT1.MAPT AND CT1.MASACH=SACH.MASACH AND
    THELOAI='TIN HOC'

--CAU2
SELECT TOP 1 WITH TIES
    DG.MADG, HOTEN, COUNT (DISTINCT THELOAI) AS TONG
FROM DOCGIA DG, PHIEUTHUE PT, CHITIET_PT CT1, SACH
WHERE DG.MADG=PT.MADG AND PT.MAPT=CT1.MAPT AND CT1.MASACH=SACH.MASACH
GROUP BY DG.MADG,HOTEN
ORDER BY TONG DESC

--CAU3
-- 3.3. Trong mỗi thể loại sách, cho biết tên sách được thuê nhiều nhất. (1 đ) 

SELECT S.TENSACH, S.THELOAI
FROM SACH S, PHIEUTHUE PT, CHITIET_PT CT 
WHERE S.MASACH = CT.MASACH AND CT.MAPT = CT.MAPT
GROUP BY S.TENSACH, S.THELOAI
HAVING COUNT(PT.MAPT)>= ALL(
    SELECT COUNT(PT.MAPT)
    FROM SACH S2, PHIEUTHUE PT, CHITIET_PT CT 
    WHERE S2.MASACH = CT.MASACH AND CT.MAPT = CT.MAPT
    GROUP BY S2.TENSACH, S2.THELOAI
    HAVING S.THELOAI = S2.THELOAI
)