CREATE DATABASE DE4
GO
USE DE4
CREATE TABLE KHACHHANG
(
    MAKH CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR
    (30),
    DIACHI VARCHAR
    (30),
    SODT VARCHAR
    (10),
    LOAIKH VARCHAR
    (10),
)

CREATE TABLE BANGDIA
(
    MABD CHAR(4) PRIMARY KEY,
    TENBD VARCHAR(25),
    THELOAI VARCHAR(25),
)


CREATE TABLE PHIEUTHUE
(
    MAPT CHAR(5) PRIMARY KEY,
    MAKH CHAR(5) PRIMARY KEY,
    NGAYTHUE smalldatetime,
    NGAYTRA smalldatetime,
    SOLUONGTHUE INT,
    CONSTRAINT FK_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)


CREATE TABLE CHITIET_PM
(
    MAPT CHAR(5),
    MABD CHAR(5),
    CONSTRAINT PK_MAPT_MABD PRIMARY KEY (MAPT,MABD),
    CONSTRAINT FK_MAPT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT),
    CONSTRAINT FK_MABD FOREIGN KEY (MABD) REFERENCES BANG_DIA(MABD),
)

-- 2.2 Trigger

GO
CREATE TRIGGER TG4_1 ON BANGDIA
FOR UPDATE, INSERT
AS
BEGIN
    DECLARE @MABD CHAR(4)
    SELECT @MABD = MABD
    FROM INSERTED
    IF EXISTS (
        SELECT *
    FROM BANGDIA
    WHERE MABD = @MABD AND
        (THELOAI <> 'CA NHAC' OR THELOAI <> 'PHIM HANH DONG' OR THELOAI <> 'PHIM TINH CAM' OR THELOAI <> 'HOAT HINH' )
    )
    BEGIN
        PRINT 'THE LOAI SAI'
    END
    ELSE
    BEGIN
        PRINT 'TAC VU THANH CONG'
    END
END

GO
CREATE TRIGGER TG4_2 ON PHIEUTHUE
FOR UPDATE, INSERT 
AS
BEGIN
    DECLARE @MaPT char(5), @MaKH char(5)
    SELECT @MaPT = MAPT, @MaKH = MAKH
    FROM INSERTED I
    IF EXISTS(
        SELECT *
    FROM KHACHHANG KH, PHIEUTHUE PT
    WHERE KH.MAKH = @MaKH and KH.MAKH = PT.MAKH AND KH.LOAIKH <> 'VIP' AND PT.SOLUONGTHUE > 5
    )
    BEGIN
        PRINT 'CHI CO KHACH VIP MOI DUOC THUE LON HON 5'
        ROLLBACK TRANSACTION
    END 
    ELSE 
    BEGIN
        PRINT 'THUE THANH CONG'
    END
END

GO
CREATE TRIGGER TG4_2 ON KHACHAHNG
FOR UPDATE 
AS
BEGIN
    DECLARE @MaKH char(5)
    SELECT @MaKH = MAKH
    FROM INSERTED I
    IF EXISTS(
        SELECT *
    FROM KHACHHANG KH, PHIEUTHUE PT
    WHERE KH.MAKH = @MaKH AND KH.MAKH = PT.MAKH AND KH.LOAIKH <> 'VIP' AND PT.SOLUONGTHUE > 5
    )
    BEGIN
        PRINT 'CHI CO KHACH VIP MOI DUOC THUE LON HON 5'
        ROLLBACK TRANSACTION
    END 
    ELSE 
    BEGIN
        PRINT 'THUE THANH CONG'
    END
END


-- 3.1

SELECT MAKH, HOTEN
FROM KHACHAHNG KH, PHIEUTHUE PT, BANGDIA BD, CHITHIET_PM CT
WHERE KH.MAKH = PT.MAKH AND PT.SOLUONGTHUE>3 AND CT.MAPT = PT.MAPT AND CT.MABD = BD.MABD AND BD.THELOAI="TINH CAM"

-- 3.2
SELECT TOP 1 WITH TIES
    KH.MAKH, KH.HOTEN
FROM KHACHHANG KH, PHIEUTHUE PT, CHITHIET_PM CT
WHERE KH.MAKH = PT.MAKH AND KH.LOAIKH = "VIP" AND CT.MAPT = PT.MAPT
GROUP BY KH.MAKH, KH.HOTEN
ORDER BY COUNT(CT.MABD) DESC

-- 3.3

SELECT KH.HOTEN, BD1.THELOAI, COUNT(DISTINCT CT.MABD)
FROM PHIEUTHUE PT, KHACHHANG KH, CHITHIET_PM CT, BANGDIA BD1
WHERE PT.MAKH = PT.MAKH AND CT.MAPT = PT.MAPT AND CT.MABD = BD1.MABD
GROUP BY KH.HOTEN, BD1.THELOAI
HAVING COUNT(CT.MABD) >=ALL(
    SELECT COUNT(DISTINCT CT.MABD)
FROM PHIEUTHUE PT, KHACHHANG KH, CHITHIET_PM CT, BANGDIA BD2
WHERE PT.MAKH = PT.MAKH AND CT.MAPT = PT.MAPT AND CT.MABD = BD2.MABD
GROUP BY KH.HOTEN, BD2.THELOAI
HAVING BD2.THELOAI = BD1.THELOAI
)