CREATE DATABASE CK1 
GO
USE CK1

CREATE TABLE LOAIPHONG
(
    MALOAIPHONG CHAR(4) PRIMARY KEY,
    TENLOAIPHONG VARCHAR(20)
)
CREATE TABLE PHONG
(
    MAPHONG CHAR(4) PRIMARY KEY,
    TENPHONG VARCHAR(20),
    MALOAIPHONG CHAR(4),
    CONSTRAINT FK_PHONG_MALOAIPHONG FOREIGN KEY (MALOAIPHONG) REFERENCES LOAIPHONG(MALOAIPHONG)
)

CREATE TABLE KHACHHANG
(
    MAKH CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(20),
    SDT VARCHAR(10),
    NGSINH SMALLDATETIME,
    GIOITINH VARCHAR(3),
)

CREATE TABLE TRANGTHAIDATCHO
(
    MATRANGTHAI CHAR(4) PRIMARY KEY,
    TENTRANGTHAI VARCHAR(50),
)

CREATE TABLE DATPHONG
(
    MADATPHONG CHAR(10) PRIMARY KEY,
    MAKH CHAR(4),
    MAPHONG CHAR(4),
    TUNGAY SMALLDATETIME,
    DENNGAY SMALLDATETIME,
    MATRANGTHAI CHAR(4),
    GHICHU VARCHAR(50),
    NGAYDAT SMALLDATETIME,

    CONSTRAINT FK_DATPHONG_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
    CONSTRAINT FK_DATPHONG_MAPHONG FOREIGN KEY (MAPHONG) REFERENCES PHONG(MAPHONG),
    CONSTRAINT FK_DATPHONG_MATRANGTHAI FOREIGN KEY (MATRANGTHAI) REFERENCES TRANGTHAIDATCHO(MATRANGTHAI)
)

SET DATEFORMAT DMY

-- THEM COT GHI CHU VARCHAR(50) VAO PHONG
ALTER TABLE PHONG ADD GHICHU VARCHAR(50)
-- SUA COT GHI CHU VARCHAR(100) PHONG
ALTER TABLE PHONG ALTER COLUMN GHICHU VARCHAR(100)
-- USE BAITHI1 
-- DROP DATABASE CK1

-- 2.1
GO
CREATE TRIGGER TG1 ON TRANGTHAIDATCHO 
FOR INSERT, UPDATE 
AS 
BEGIN
    DECLARE @TENTRANGTHAI VARCHAR(50)
    SELECT @TENTRANGTHAI = TENTRANGTHAI
    FROM inserted

    -- IF EXISTS(
    --     SELECT *
    --     FROM TRANGTHAIDATCHO
    --     WHERE TENTRANGTHAI<>'HOANTAT' OR TENTRANGTHAI<>'KHONGTHANHCONG'
    -- )
    IF(@TENTRANGTHAI = 'HOANTAT' OR @TENTRANGTHAI = 'KHONGTHANHCONG')
    BEGIN
        PRINT @TENTRANGTHAI
        PRINT 'TAC VU CHO TRANGTHAIDATCHO THANH CONG'

    END 
    ELSE 
    BEGIN
        PRINT @TENTRANGTHAI
        PRINT 'TEN TRANG THAI CHI CO THE LA HOANTAT HOAC KHONG THANHCONG'
        ROLLBACK TRANSACTION
    END
END


-- 2.2 

GO
CREATE TRIGGER TG2 ON DATPHONG 
FOR INSERT 
AS 
BEGIN
    DECLARE @MAKH CHAR(4), @NGAYDAT SMALLDATETIME, @NGSINH SMALLDATETIME, @MADATPHONG CHAR(4)
    SELECT @MAKH=MAKH, @NGAYDAT = NGAYDAT, @MADATPHONG = MADATPHONG
    FROM inserted

    SELECT @NGSINH = KH.NGSINH
    FROM KHACHHANG KH
    WHERE KH.MAKH = @MAKH

    IF (@NGSINH = @NGAYDAT)
    BEGIN
        PRINT @NGSINH
        PRINT @NGAYDAT
        PRINT 'CHUC MUNG BAN DUOC KHUYEN MAI'
        UPDATE DATPHONG
        SET GHICHU = 'SINH NHAT CUA KHACH HANG'
        WHERE MADATPHONG = @MADATPHONG
    END
    ELSE
    BEGIN
        PRINT @NGSINH
        PRINT @NGAYDAT
        PRINT 'KHONG CO KHUYEN MAI GI'
    END
END

GO
INSERT INTO LOAIPHONG
    (MALOAIPHONG, TENLOAIPHONG)
VALUES('LP01', 'LPA')
INSERT INTO LOAIPHONG
    (MALOAIPHONG, TENLOAIPHONG)
VALUES('LP02', 'LPB')
INSERT INTO LOAIPHONG
    (MALOAIPHONG, TENLOAIPHONG)
VALUES('LP03', 'LPC')

INSERT INTO PHONG
    (MAPHONG,TENPHONG, MALOAIPHONG)
VALUES('MP01', 'PABC', 'LP01')
INSERT INTO PHONG
    (MAPHONG,TENPHONG, MALOAIPHONG)
VALUES('MP02', 'PDEF', 'LP01')
INSERT INTO PHONG
    (MAPHONG,TENPHONG, MALOAIPHONG)
VALUES('MP03', 'PGHI', 'LP01')

INSERT INTO KHACHHANG
    (MAKH, HOTEN, SDT, NGSINH, GIOITINH)
VALUES('KH01', 'KHA', '020202', '02/02/2020', 'NAM')
INSERT INTO KHACHHANG
    (MAKH, HOTEN, SDT, NGSINH, GIOITINH)
VALUES('KH02', 'KHB', '020202', '03/03/2020', 'NAM')
INSERT INTO KHACHHANG
    (MAKH, HOTEN, SDT, NGSINH, GIOITINH)
VALUES('KH03', 'KHC', '020202', '04/04/2020', 'NAM')

INSERT INTO TRANGTHAIDATCHO
    (MATRANGTHAI, TENTRANGTHAI)
VALUES('TT01', 'HOANTAT')
INSERT INTO TRANGTHAIDATCHO
    (MATRANGTHAI, TENTRANGTHAI)
VALUES('TT02', 'KHONGTHANHCONG')
-- INSERT INTO TRANGTHAIDATCHO(MATRANGTHAI, TENTRANGTHAI) VALUES('TT03', 'CC')

INSERT INTO DATPHONG
    (MADATPHONG, MAKH, MAPHONG, TUNGAY, DENNGAY, MATRANGTHAI, GHICHU, NGAYDAT)
VALUES('DP01', 'KH01', 'MP01', '02/03/2020', '03/04/2020', 'TT01', 'OK', '06/06/2020')
INSERT INTO DATPHONG
    (MADATPHONG, MAKH, MAPHONG, TUNGAY, DENNGAY, MATRANGTHAI, GHICHU, NGAYDAT)
VALUES('DP02', 'KH02', 'MP01', '02/03/2020', '03/04/2020', 'TT02', 'OK', '24/02/2020')
INSERT INTO DATPHONG
    (MADATPHONG, MAKH, MAPHONG, TUNGAY, DENNGAY, MATRANGTHAI, GHICHU, NGAYDAT)
VALUES('DP03', 'KH01', 'MP01', '02/03/2020', '03/04/2020', 'TT01', 'OK', '09/09/2020')

-- -- 3.1
-- SELECT DP.MADATPHONG, TUNGAY, DENNGAY, TTDC.TENTRANGTHAI
-- FROM DATPHONG DP, TRANGTHAIDATCHO TTDC
-- WHERE DP.MATRANGTHAI = TTDC.MATRANGTHAI

-- -- 3.2 

-- SELECT P.MAPHONG, TENPHONG, COUNT(DP.MADATPHONG) AS SOLANPHONGNAYDUOCDAT
-- FROM PHONG P, DATPHONG DP
-- WHERE P.MAPHONG = DP.MAPHONG AND MONTH(DP.NGAYDAT)=5 AND YEAR(DP.NGAYDAT)=2020
-- GROUP BY P.MAPHONG, TENPHONG

-- -- 3.3 

-- SELECT TOP 1 WITH TIES MONTH(DP.NGAYDAT) AS THANG
-- FROM DATPHONG DP
-- WHERE YEAR(DP.NGAYDAT)=2019
-- GROUP BY MONTH(DP.NGAYDAT)
-- ORDER BY COUNT(DP.MADATPHONG) DESC


-- -- 3.4
SELECT KH.MAKH, HOTEN 
FROM KHACHHANG KH, DATPHONG DP
WHERE DP.MAKH = KH.MAKH AND DP.NGAYDAT='6/6/2020'

intersect

SELECT KH.MAKH, HOTEN 
FROM KHACHHANG KH, DATPHONG DP
WHERE DP.MAKH = KH.MAKH AND DP.NGAYDAT='9/9/2020'

-- -- 3.5 

-- SELECT MAPHONG, TENPHONG 
-- FROM PHONG P
-- WHERE NOT EXISTS(
--     SELECT * 
--     FROM KHACHHANG KH
--     WHERE NOT EXISTS (
--         SELECT * 
--         FROM DATPHONG DP 
--         WHERE DP.MAKH = KH.MAKH 
--         AND DP.MAPHONG = P.MAPHONG
--         AND MONTH(DP.NGAYDAT)=2
--         AND YEAR(DP.NGAYDAT)=2020
--     )
-- )