-- GK1 2019-2020
-- 1
ALTER TABLE KHOAHOC ADD CONSTRAINT KHOAHOC_NGDK_NGKT CHECK(NGDK<=NGKT)
-- 2
ALTER TABLE HOCPHAN ADD GHICHU VARCHAR(100)
-- 3
DELETE FROM CTDK
WHERE (SONGAYHT < 3)
-- 4
UPDATE HOCPHAN
SET BATBUOC = 1
WHERE (MAHP = 'AV100' AND TUAN = 15)
